stages:
  - build

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository

# This will only validate and compile stuff and run e.g. maven-enforcer-plugin.
# Because some enforcer rules might check dependency convergence and class duplications
# we use `test-compile` here instead of `validate`, so the correct classpath is picked up.
build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day
